// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTick():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function IsPaused():Promise<boolean>;

export function ListScenarios():Promise<Array<string>>;

export function LoadScenario(arg1:string,arg2:number):Promise<void>;

export function Pause():Promise<void>;

export function Resume():Promise<void>;

export function StartRun(arg1:number):Promise<void>;

export function Stop():Promise<void>;
