// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {api} from '../models';

export function CurrentTick():Promise<number>;

export function GetDeposit(arg1:entity.EntityId):Promise<api.DepositView>;

export function GetDeposits(arg1:entity.EntityId):Promise<Array<api.DepositView>>;

export function GetFactions():Promise<Array<api.FactionView>>;

export function GetTerritories():Promise<Array<api.TerritoryView>>;

export function GetTerritory(arg1:entity.EntityId):Promise<api.TerritoryView>;

export function Greet(arg1:string):Promise<string>;

export function IsPaused():Promise<boolean>;

export function ListScenarios():Promise<Array<string>>;

export function LoadScenario(arg1:string,arg2:number):Promise<void>;

export function Pause():Promise<void>;

export function Resume():Promise<void>;

export function StartRun(arg1:number):Promise<void>;

export function Stop():Promise<void>;
