// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTick() {
  return window['go']['main']['App']['CurrentTick']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function ListScenarios() {
  return window['go']['main']['App']['ListScenarios']();
}

export function LoadScenario(arg1, arg2) {
  return window['go']['main']['App']['LoadScenario'](arg1, arg2);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
