// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTick() {
  return window['go']['main']['App']['CurrentTick']();
}

export function DispatchDrones(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DispatchDrones'](arg1, arg2, arg3, arg4);
}

export function GetDeposit(arg1) {
  return window['go']['main']['App']['GetDeposit'](arg1);
}

export function GetDeposits(arg1) {
  return window['go']['main']['App']['GetDeposits'](arg1);
}

export function GetDrones() {
  return window['go']['main']['App']['GetDrones']();
}

export function GetFactions() {
  return window['go']['main']['App']['GetFactions']();
}

export function GetTerritories() {
  return window['go']['main']['App']['GetTerritories']();
}

export function GetTerritory(arg1) {
  return window['go']['main']['App']['GetTerritory'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function ListScenarios() {
  return window['go']['main']['App']['ListScenarios']();
}

export function LoadScenario(arg1, arg2) {
  return window['go']['main']['App']['LoadScenario'](arg1, arg2);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function RecallDrones(arg1, arg2) {
  return window['go']['main']['App']['RecallDrones'](arg1, arg2);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function StartRun(arg1) {
  return window['go']['main']['App']['StartRun'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
